// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcVzn7ld7MgpfNceQ4vUph66By1A7Qrsw',
    appId: '1:590220348303:android:cbb68bf8a149edfbec19fa',
    messagingSenderId: '590220348303',
    projectId: 'crud-app-831e6',
    storageBucket: 'crud-app-831e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoORTW5Fd_8i1RDrO3G_4ccSdnc0sDRQk',
    appId: '1:590220348303:ios:f97a3f53bab3eb59ec19fa',
    messagingSenderId: '590220348303',
    projectId: 'crud-app-831e6',
    storageBucket: 'crud-app-831e6.appspot.com',
    iosBundleId: 'com.example.simpleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoORTW5Fd_8i1RDrO3G_4ccSdnc0sDRQk',
    appId: '1:590220348303:ios:f97a3f53bab3eb59ec19fa',
    messagingSenderId: '590220348303',
    projectId: 'crud-app-831e6',
    storageBucket: 'crud-app-831e6.appspot.com',
    iosBundleId: 'com.example.simpleApp',
  );
}
